config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = t "main_title"
    if page_title.blank?
      base_title
    else
      page_title + " " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t("footer_content1") %><%= link_to t("footer_link1"), "http://www.railstutorial.org/" %>
    <%= t("footer_content2") %><%= link_to t("footer_link2"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("footer_link3"), about_path %></li>
      <li><%= link_to t("footer_link4"), contact_path %></li>
      <li><%= link_to t("footer_link5"), "http://news.railstutorial.org/"%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("header_link1"), root_path %></li>
        <li><%= link_to t("header_link2"), help_path %></li>
        <li><%= link_to t("header_link3"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %><%= t "main_title" %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".header" %></h1>
<p>
  <%= t ".content1" %><em><%= link_to t(".link1"),
                              "http://www.railstutorial.org/" %></em>
  <%= t ".content2" %>
  <%= link_to t(".link2"), "http://www.railstutorial.org/book" %>
  <%= t ".content3" %>
  <%= link_to t(".link3"), "http://screencasts.railstutorial.org/" %>
  <%= t ".content4" %>
  <%= link_to t(".link4"), "http://rubyonrails.org/" %>.
  <%= t ".content5" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".header" %></h1>
<p>
  <%= t ".content1" %>
  <%= link_to t(".link1"), "http://www.railstutorial.org/contact" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".header" %></h1>
<p>
  <%= t ".content1" %>
  <%= link_to t(".link1"), "http://www.railstutorial.org/help" %>.
  <%= t ".content2" %>
  <em><%= link_to t(".link2"), "http://www.railstutorial.org/book" %></em>.
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t ".header1" %></h1>
  <h2>
    <%= t ".header2_0" %>
    <%= link_to t(".link1"), "http://www.railstutorial.org/" %>
    <%= t ".header2_1" %>
  </h2>
  <%= link_to t(".link2"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: t(".logo_alt")), "http://rubyonrails.org/" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>